# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ztsnb',
                'doc_host': 'https://szagar.github.io',
                'git_url': 'https://github.com/szagar/ztsnb',
                'lib_path': 'ztsnb'},
  'syms': {'ztsnb.core': {'ztsnb.core.foo': ('core.html#foo', 'ztsnb/core.py')}}}
